---
metadata:
  title: "Liam's Minecraft Podcast"
  description: "Liam spricht über minecraft"
  language: "de-at"
  link: "https://liamebarlow.b-cdn.net/minecraft-podcast/"
  itunes_image: "https://liamebarlow.b-cdn.net/minecraft-podcast/pickaxe.png"
  itunes_category: "Video Games"
  itunes_explicit: false
  itunes_author: "Liam"
  itunes_email: "podcast@nutmeg.at"
  rss_feed_url: "https://liamebarlow.github.io/minecraft-podcast/podcast_feed.xml"
  guid: "a7019889-2302-5272-b468-7055cfc6b63f"

episodes:
  - title: "Minecraft Monster"
    description: "In dieser episode spreche ich über monster und erkläre wie man sie am besten beseigt" 
    publication_date: "2023-04-22T10:00:00"
    asset_url: "https://liamebarlow.b-cdn.net/minecraft-podcast/podcast 1.mp3"
    episode: 1
    season: 1
    episode_type: "full"
    itunes_explicit: false
    
  - title: "PVP (Player versus Player)"
    description: "In diser episode spreche ich über PVP und wie man gewinnt" 
    publication_date: "2023-05-01T10:00:00"
    asset_url: "https://liamebarlow.b-cdn.net/minecraft-podcast/podcast 2 (pvp).mp3"
    episode: 2
    season: 1
    episode_type: "full"
    itunes_explicit: false

  - title: "Biome"
    description: "In dieser episode spreche ich über die vielen verscheidenen biome in minecraft" 
    publication_date: "2023-05-14T10:00:00"
    asset_url: "https://liamebarlow.b-cdn.net/minecraft-podcast/podcast 3 (biomes ).mp3"
    episode: 3
    season: 1
    episode_type: "full"
    itunes_explicit: false

  - title: "Friedliche wesen"
    description: "In dieser episode spreche ich über die vielen friedlichen wesen in minecraft" 
    publication_date: "2023-06-02T10:00:00"
    asset_url: "https://liamebarlow.b-cdn.net/minecraft-podcast/podcast 4 passive mobs.mp3"
    episode: 4
    season: 1
    episode_type: "full"
    itunes_explicit: false

  - title: "Die Nervigsten Monster"
    description: "In Dieser episode habe ich einen gast in meinem podcast nämlich meinen freund Tobi !. Wir übelegen welche monster wir am nervigsten finden" 
    publication_date: "2023-06-14T10:00:00"
    asset_url: "https://liamebarlow.b-cdn.net/minecraft-podcast/podcast 5 mit tobi.mp3"
    episode: 5
    season: 1
    episode_type: "full"
    itunes_explicit: false
